In [83]:
import requests


def gdrive_link(file_id):
    return 'https://drive.google.com/uc?export=download&id={}'.format(file_id)


def parse(string):
    string = string.decode("utf-8")
    string = string.strip("'")
    string = string.split("'	'")
    return string

#get column headers for counts matrix data
#[labels for all 122 classes for manual annotation; 122 columns, 1 row] column headers for counts matrix data
file_id = '0B8AIZXhts0nWQ3c1TmRqUXRDMlE'
link = gdrive_link(file_id)
r = requests.get(link)
col_headers = r.content
col_headers = parse(col_headers)


#get labels for ciliate classes
# [subset of labels for 27 ciliate classes; 27 columns, 1 row] [note: maximum richness 27 for the plot]
file_id = '0B8AIZXhts0nWbmxUWFRtaUdRSXc'
link = gdrive_link(file_id)
r = requests.get(link)
cil_labels = r.content
cil_labels = parse(cil_labels)

#get rows labeled by date for counts matrix data
#[07-Jun-2006 to 22-Feb-2017; 1 column, 543 rows] 
file_id = '0B8AIZXhts0nWUFV2UlR3VGl0cjg'
link = gdrive_link(file_id)
r = requests.get(link)
dates = r.text
dates = dates.split("\r")
for i in range(len(dates)):
    dates[i] = dates[i].replace("'","")

#get counts matrix data
#count per class per date for all 122 classes; 122 columns, 543 rows];
file_id = '0B8AIZXhts0nWNzBIcnRvTFZzTVk'
link = gdrive_link(file_id)
r = requests.get(link)
counts_data = r.text
counts_matrix = []
count = 0
temp_mat = []
num = ''
for x in counts_data:
    if x != '\t' and x != '\r':
        num += x
    if x == '\t' or x == '\r':
        temp_mat.append(num)
        num = ''
        count +=1 
    if count == 122:
        counts_matrix.append(temp_mat)
        count = 0
        temp_mat = []
counts_matrix.append(temp_mat)

#this is a 2nd matrix of ml_analyzed per class per date for all 122 classes; 
#122 columns, should be 543 rows - remove last row of NaNs
#if a class has an NaN for a particular date then it could not be adequately observed / exclude that class]
file_id = '0B8AIZXhts0nWOXhjRnZ2YWtWa1U'
link = gdrive_link(file_id)
r = requests.get(link)
ml_analyzed = r.text
ml_matrix = []
count = 0
temp_mat = []
num = ''
for x in ml_analyzed:
    if x != '\t' and x != '\r' and x != '\n':
        num += x
    if x == '\t' or x == '\r':
        temp_mat.append(num)
        num = ''
        count +=1 
    if count == 122:
        ml_matrix.append(temp_mat)
        count = 0
        temp_mat = []
del ml_matrix[-1]

for x in range(len(ml_matrix)):
    for i in range(len(ml_matrix[x])):
        if ml_matrix[x][i] != 'NaN':
            ml_matrix[x][i] = float(ml_matrix[x][i])

In [88]:
counts_mat = pd.DataFrame.from_records(counts_matrix, columns=col_headers)
counts_mat.index = dates
counts_mat.index = df.index.to_datetime()
print(df)

           Asterionellopsis Ceratium Chaetoceros Corethron Cylindrotheca  \
2006-06-07                0        0          78         0           142
2006-06-14                0        2           0         0             0
2006-06-20                3        2         357         0            71
2006-06-21                2        2         231         0            19
2006-07-09                0        0           0         3             0
2006-07-10                2        0         276         1            21
2006-07-14                0        2           0         5             0
2006-07-17               16        0         390         2            18
2006-07-24                5        6         116         2            14
2006-07-27                0        0          33         0            11
2006-07-29                0        2           0         8             0
2006-08-25                2        5         336        24            22
2006-08-26                0        1         103         6             4
2006-08-28                0       12           0        27             0
2006-09-27                0        4          99         1             2
2006-09-28                0        4           0         1             0
2006-09-29                0        1          45         1             5
2006-10-01                0        0           0         0             0
2006-10-07                0        6          97         0            13
2006-10-11                0        0           0         0             0
2006-10-12                0       12           0         0             0
2006-10-13                0        0           0         0             0
2006-10-22                0       11          33         0             1
2006-10-27                0       26           0         0             0
2006-11-03                8        0         271         1             8
2006-11-05                2        0         210         1            15
2006-11-06                0        2           0         5             0
2006-12-19                0        2           0        69             0
2006-12-20                2        0         229        15            24
2006-12-26                0        1           0       154             0
...                     ...      ...         ...       ...           ...
2016-03-04                1        0           8         3           176
2016-03-17                0        2          10         3           256
2016-03-30                0        0           4         0            90
2016-04-14                0        1           2         0          1474
2016-04-19                0        1           7         0          5064
2016-05-14                0        0           3         0            50
2016-05-26                0        2           7         0           144
2016-06-10                0       12         166         0           155
2016-06-15                0        5         770         0           379
2016-06-28                2        6         129         0            41
2016-07-13               13        4         461         0            45
2016-07-28               10        1        1827         2           264
2016-08-09               11        0         874         0           169
2016-08-19                1        0         635         0            32
2016-08-24                3        0        1143         2           111
2016-09-02                7        0         328         1           115
2016-09-22                0        0          72         0             1
2016-09-23                0        0          93         0            16
2016-10-07                0        0         114         0            27
2016-10-27                0        0         476         0            80
2016-11-04                0        0         968         0           161
2016-11-09                0        0         342         0            25
2016-11-19                0        0          24         0            12
2016-11-28                0        0          24         4             1
2016-12-14                0        1          12         4            41
2016-12-24               12        0          36        12           233
2017-01-06               15        0          76        14           362
2017-01-15                0        1          93        14           271
2017-02-05                0        0          22         3            62
2017-02-22                0        0           0         0             0

           DactFragCerataul Dactyliosolen Dictyocha Dinobryon Ditylum  \
2006-06-07                3            18         3         6       1
2006-06-14                0            35         0        15       0
2006-06-20              123            18         0        39       0
2006-06-21                0            10         0         1       0
2006-07-09                0           124         0         6       0
2006-07-10               12            58         0         1       0
2006-07-14                0            43         0         0       0
2006-07-17                0            43         0         1       0
2006-07-24                3            14         0         0       0
2006-07-27                0             2         0         0       0
2006-07-29                0             0         0         0       2
2006-08-25                5             2         0         3       3
2006-08-26                0             1         0         1       0
2006-08-28                0             1         0         0       4
2006-09-27                0             4         1        29       1
2006-09-28                0            22         0        58       0
2006-09-29                1             6         1         8       0
2006-10-01                0             0         0         0       0
2006-10-07                0            15         0         5       1
2006-10-11                0             0         0         0       0
2006-10-12                0            23         6         8       0
2006-10-13                0             0         0         0       0
2006-10-22                0             0        11         0       1
2006-10-27                0             0        12         0       0
2006-11-03               11             0         0         0       0
2006-11-05               27             1         0         0       0
2006-11-06                0             0         4         0       0
2006-12-19                0             0        95         0       0
2006-12-20              275             0        51         0       0
2006-12-26                0             1       120         0       1
...                     ...           ...       ...       ...     ...
2016-03-04                7             2         2        18       1
2016-03-17               25             1         1       263       1
2016-03-30                1             0         0       182       0
2016-04-14                1             0         0        95       0
2016-04-19                0             0         0       107       0
2016-05-14                1             0         0        25       0
2016-05-26                0             0         0         0       0
2016-06-10                0             1         0        84       0
2016-06-15                2             2         0        22       0
2016-06-28                6            33         0         3       0
2016-07-13                1            83         0         0       0
2016-07-28                0            40         0         1       0
2016-08-09                4            35         2         1       0
2016-08-19                1            99         0        39       0
2016-08-24               18           172         0       142       0
2016-09-02                2            46         0        16       0
2016-09-22                0             2         0        29       0
2016-09-23                0             5         1        40       0
2016-10-07                0            13         0         4       0
2016-10-27                0             4         3        78       0
2016-11-04                0             5         1         5       0
2016-11-09                0             3         0        13       0
2016-11-19                0             0         5         0       0
2016-11-28                0             2        25         0       0
2016-12-14                1             9         0         0       4
2016-12-24                1             7         0         1       3
2017-01-06                4            10         0        18      12
2017-01-15                2            28         1       452       4
2017-02-05                0             1         0         2       0
2017-02-22                0             0         0         0       0

               ...     zooplankton camera_spot Eutintinnus Favella  \
2006-06-07     ...               0           0           4       0
2006-06-14     ...               0           0           0       0
2006-06-20     ...               0          11           0       0
2006-06-21     ...               0          69           0       0
2006-07-09     ...               0           0           0       0
2006-07-10     ...               0           0           0       0
2006-07-14     ...               0           0           0       0
2006-07-17     ...               0          17           0       0
2006-07-24     ...               0         248           0       0
2006-07-27     ...               0          17           0       0
2006-07-29     ...               0           0           0       0
2006-08-25     ...               1           0           0       0
2006-08-26     ...               0           0           0       0
2006-08-28     ...               0           0           0       0
2006-09-27     ...               0           0           0       0
2006-09-28     ...               0           0           0       0
2006-09-29     ...               1           0           0       0
2006-10-01     ...               0           0           0       0
2006-10-07     ...               1           0           1       0
2006-10-11     ...               0           0           0       0
2006-10-12     ...               0           0           1       0
2006-10-13     ...               0           0           0       0
2006-10-22     ...               0           0           0       0
2006-10-27     ...               0           0           0       0
2006-11-03     ...               0         370           0       0
2006-11-05     ...               0           4           0       0
2006-11-06     ...               0           0           0       0
2006-12-19     ...               0           0           0       0
2006-12-20     ...               0           0           0       0
2006-12-26     ...               0           0           0       0
...            ...             ...         ...         ...     ...
2016-03-04     ...               0           0           0       0
2016-03-17     ...               0           0           0       0
2016-03-30     ...               1           0           0       0
2016-04-14     ...               0           0           0       0
2016-04-19     ...               0           0           0       0
2016-05-14     ...               0           0           0       0
2016-05-26     ...               0           0           0       0
2016-06-10     ...               0           0           0       0
2016-06-15     ...               1           0           0       0
2016-06-28     ...               0           0           0       0
2016-07-13     ...               0           0           0       0
2016-07-28     ...               0           0           0       0
2016-08-09     ...               2           0           0       0
2016-08-19     ...               0           0           0       0
2016-08-24     ...               2           0           0       0
2016-09-02     ...               1           0           0       0
2016-09-22     ...               1           0           1       0
2016-09-23     ...               1           0           1       1
2016-10-07     ...               0           0           0       0
2016-10-27     ...               0           0           0       0
2016-11-04     ...               0           0           0       0
2016-11-09     ...               0           0           0       0
2016-11-19     ...               0           0           0       0
2016-11-28     ...               0           0           0       0
2016-12-14     ...               0           0           0       0
2016-12-24     ...               0           0           0       0
2017-01-06     ...               1           0           0       0
2017-01-15     ...               0           0           0       0
2017-02-05     ...               0           0           0       0
2017-02-22     ...               0           0           0       0

           Helicostomella_subulata Stenosemella_sp1 Stenosemella_sp2  \
2006-06-07                       0                0                0
2006-06-14                       0                1                0
2006-06-20                       0                1                0
2006-06-21                       0                0                0
2006-07-09                       0                1                0
2006-07-10                       0                0                0
2006-07-14                       0                0                0
2006-07-17                       0                0                0
2006-07-24                       0                0                0
2006-07-27                       0                0                0
2006-07-29                       0                0                0
2006-08-25                       0                0                0
2006-08-26                       0                0                0
2006-08-28                       0                0                0
2006-09-27                       0                0                0
2006-09-28                       0                0                0
2006-09-29                       0                0                0
2006-10-01                       0                0                0
2006-10-07                       0                0                0
2006-10-11                       0                0                0
2006-10-12                       0                0                0
2006-10-13                       0                0                0
2006-10-22                       0                0                0
2006-10-27                       0                0                0
2006-11-03                       0                0                0
2006-11-05                       0                3                2
2006-11-06                       0                1                2
2006-12-19                       0                0                4
2006-12-20                       0                1                1
2006-12-26                       0                1                6
...                            ...              ...              ...
2016-03-04                       0                0                0
2016-03-17                       0                0               15
2016-03-30                       0                0                0
2016-04-14                       0                0                0
2016-04-19                       0                0                2
2016-05-14                       0                0                0
2016-05-26                       0                0                0
2016-06-10                       0                0                0
2016-06-15                       0                0                0
2016-06-28                       0                0                0
2016-07-13                       0                0                0
2016-07-28                       0                0                0
2016-08-09                       0                0                0
2016-08-19                       0                0                0
2016-08-24                       0                0                0
2016-09-02                       0                0                0
2016-09-22                       0                0                0
2016-09-23                       0                0                0
2016-10-07                       0                0                0
2016-10-27                       0                0                0
2016-11-04                       0                0                0
2016-11-09                       0                0                0
2016-11-19                       0                0                0
2016-11-28                       0                0                2
2016-12-14                       0                2                0
2016-12-24                       0                0                0
2017-01-06                       0                0                1
2017-01-15                       0                0                0
2017-02-05                       0                0                0
2017-02-22                       0                0                0

           Tintinnidium Tintinnopsis Balanion_sp
2006-06-07            0            0           0
2006-06-14            0            3           0
2006-06-20            0            4           0
2006-06-21            0            0           0
2006-07-09            0            1           0
2006-07-10            0            0           0
2006-07-14            0            0           0
2006-07-17            0            0           0
2006-07-24            0            0           0
2006-07-27            0            0           0
2006-07-29            0            0           0
2006-08-25            0            0           2
2006-08-26            0            0           0
2006-08-28            0            2           0
2006-09-27            0            0           1
2006-09-28            0            1           0
2006-09-29            0            1           1
2006-10-01            0            0           0
2006-10-07            0            6           2
2006-10-11            0            0           0
2006-10-12            0            4           0
2006-10-13            0            0           0
2006-10-22            0            0           0
2006-10-27            0            0           0
2006-11-03            0            0           0
2006-11-05            0            1           1
2006-11-06            0            5           0
2006-12-19            0            3           0
2006-12-20            0            0          20
2006-12-26            0            0           0
...                 ...          ...         ...
2016-03-04            0            1           4
2016-03-17            2           23          20
2016-03-30            0           10           6
2016-04-14            0            2           1
2016-04-19            0            4           3
2016-05-14            0            0           0
2016-05-26            0            0           0
2016-06-10            0            4          10
2016-06-15            0            3           0
2016-06-28            0            0           2
2016-07-13            0            5          11
2016-07-28            0            7          19
2016-08-09            0            3           0
2016-08-19            2            8           3
2016-08-24            0            7           4
2016-09-02            0            1           0
2016-09-22            0            1           2
2016-09-23            2            1           4
2016-10-07            0            1           6
2016-10-27            0            0           0
2016-11-04            0            0           0
2016-11-09            0            5           0

/Users/sydruzicka/desktop/ENTER/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: to_datetime is deprecated. Use pd.to_datetime(...)
  This is separate from the ipykernel package so we can avoid doing imports until